version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres_c
    restart: always
    environment:
      POSTGRES_DB: ecom_db
      POSTGRES_USER: ecom_user
      POSTGRES_PASSWORD: ecom_ps
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./backend
    container_name: fastapi_c
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://ecom_user:ecom_ps@db:5432/ecom_db
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: frontend_c
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
